name: Push automatically to Chocolatey

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'new-version')
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Chocolatey
        run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iwr https://community.chocolatey.org/install.ps1 -UseBasicParsing | iex

      - name: Set Chocolatey API key
        run: choco apikey --key ${{ secrets.CHOCO_API_KEY }} --source https://push.chocolatey.org/

      - name: Find and push package to Chocolatey
        run: |
          $nupkgFile = Get-ChildItem -Path . -Filter *.nupkg | Select-Object -First 1
          if ($null -eq $nupkgFile) {
            Write-Error "No .nupkg file found."
            exit 1
          }
          choco push $nupkgFile.FullName --source https://push.chocolatey.org/
